### ISSUE TITLE
Restarting ST3 does not toggle HighlightWhitespaces

### ISSUE THREAD

**Issue by xkryptor** [disq/HighlightWhitespaces#12]
After installing HighlightWhitespaces and restarting ST3, I cannot toggle HighlightWhitespaces with Ctrl+Alt+W

**Comment by gprasant** [comment]
@disq  / @popsikle what version of the package / ST3 should I use for a working version of this plugin ?

**Comment by popsikle** [comment]
@disq has not been around this repo for a while.  Im currently asking the package control people to point the package control link to my repo instead via this pr https://github.com/wbond/package_control_channel/pull/4487 but you can clone my fork and test it out via https://github.com/popsikle/HighlightWhitespaces

**Comment by disq** [comment]
Well, you could've sent a pull request ;)

**Comment by gprasant** [comment]
I've tested that @popsikle 's version works in ST3. So, if this change does not regress any feature in ST2, it better if this were a PR in @disq's repo because the current repo already has 11K installs and it might just be confusing if suddenly there was a difference in the source of the package. 

@popsikle - can you raise a PR here ? 
and can you close  wbond/package_control_channel#4487  without any changes ?

**Comment by popsikle** [comment]
Hey @disq you are alive! Ill open a PR =)

**Comment by gprasant** [comment]
I just love it when people meet after a long time on open source.

**Comment by disq** [comment]
Merged :)

**Comment by gprasant** [comment]
Any update needed on sublime.Wbond.net?

**Comment by disq** [comment]
No, I tagged a new release, wbond should get updated soon.
